### ISSUE TITLE
A very good video-related work, it is convenient to open source the data set？

### ISSUE THREAD

**Issue by Xujianzhong** [RenShuhuai-Andy/TimeChat#1]

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interest.

We just released our instruction-tuning dataset in https://huggingface.co/datasets/ShuhuaiRen/TimeIT, please refer to https://github.com/RenShuhuai-Andy/TimeChat/blob/master/docs/DATA.md for more details on downloading and processing video data.
