### ISSUE TITLE
Details of sliding qformer operation

### ISSUE THREAD

**Issue by jihwanp** [RenShuhuai-Andy/TimeChat#11]
Hi, thanks for providing wonderful work.

In the paper, I cannot find the details of sliding qformer operations. How do output queries in qformer from different frames interact with each other? Which module is used for interaction?

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interest.

The usage of sliding video-qformer is in: 
https://github.com/RenShuhuai-Andy/TimeChat/blob/master/timechat/models/timechat.py#L327-L345
