### ISSUE TITLE
RAM and VRAM requirement

### ISSUE THREAD

**Issue by Coronal-Halo** [RenShuhuai-Andy/TimeChat#13]
Is there any way that this program can run with 16 or 24 GB of VRAM?

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interest.

You can try installing the [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) library and add `model_config.low_resource = True` in https://github.com/RenShuhuai-Andy/TimeChat/blob/master/demo.ipynb. This will load the LLAMA model in 8-bit precision, potentially enabling the model to run with 24 GB of VRAM, see https://github.com/RenShuhuai-Andy/TimeChat/blob/master/timechat/models/timechat.py#L139. However, I cannot guarantee the performance of the 8-bit LLAMA model.

**Comment by onlyonewater** [comment]
I set the low_resource as false, and the memory of the GPU is only 18G, so I think a 24G GPU like 3090 is enough for inference.
