### ISSUE TITLE
Demo can‘t show the same desult

### ISSUE THREAD

**Issue by xiaoxiaoli666** [RenShuhuai-Andy/TimeChat#15]
hello,thank you for your contribution.
I met a question when run the demo.demo.ipynb,as the result can‘t be like yours.
It's so short.how can I get a long and detailed description?also, the demo can't run on gpu,it run on cpu. The environment is as your readme.How can I put it on gpu? 
thank you!

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interest.

The following line in demo.ipynb will put the model to gpu0:
![image](https://github.com/RenShuhuai-Andy/TimeChat/assets/30052148/63272473-8cb9-48c2-83e5-ebfa17402a86)
make sure your torch supports gpus (you can run `python -c"import torch; print(torch.cuda.is_available())"` to verify this, the expected output should be `True`).

For the output, what does the output on your device look like? Or can you just re-run the inference multiple times to see if the output is long and detailed?
