### ISSUE TITLE
Inquiry on training cost

### ISSUE THREAD

**Issue by HenryHZY** [RenShuhuai-Andy/TimeChat#16]
Hi @RenShuhuai-Andy @yaolinli , thanks for your great projects!
As stated in the paper, "using a batch size of 32, with a single 8-V100 (32G) machine". 
I am interested in reproducing the training and would like to ask about the training time cost of TimeChat.

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interest.

It takes about 2 days to finish the training

**Comment by HenryHZY** [comment]
Thanks for the information!
