### ISSUE TITLE
What is the relationship between segment and timetoken？

### ISSUE THREAD

**Issue by sunwhw** [RenShuhuai-Andy/TimeChat#17]
Hi, thanks for you great work! I want to ask what is the relationship between original segment(contained in seg_prompt) and time_token_？
<img width="1170" alt="image" src="https://github.com/RenShuhuai-Andy/TimeChat/assets/48038000/aab12ed8-4935-4e8c-9922-7f3135cbc533">

**Comment by sunwhw** [comment]
Is asr data used when constructing instruction data?

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interest.

The time token is used in [Vid2seq](https://arxiv.org/abs/2302.14115), which uses relative timestampes. Specifically, it quantizes any video of duration $T_i$ into 100 equally-spaced timestamps. 

In contrast, we use absolute timestamps, i.e., original segments contained in seg_prompts. The first number in seg_prompts denotes the duration (seconds) of current video. After that, each two numbers represent the start and end time of a fragment. 

The training on TimeIT-104k uses asr data, while the fine-tuning or evaluation on Youcook2, Charades, and qvhighlight do not use asr data.

**Comment by sunwhw** [comment]
oh, thanks for your clear reply!
