### ISSUE TITLE
Question about prompts.

### ISSUE THREAD

**Issue by gyxxyg** [RenShuhuai-Andy/TimeChat#18]
Thank you for your excellent work!

I have a few questions regarding the prompts while constructing the IT data. For instance, in `utils/construct_it_data/process_dvc_data.py`, the prompt file is `prompts/dvc_prompts.json`. However, I only found `/prompts/dvc_description.txt`, which appears to be related. Could you kindly inform me if I have overlooked something, or would you mind updating the scripts in 'utils/construct_it_data/' to ensure they are consistent with the current version?

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interests.

We have uploaded the prompts for constructing the instruction data. https://github.com/RenShuhuai-Andy/TimeChat/tree/master/utils/construct_it_data/prompts

**Comment by gyxxyg** [comment]
Thank you so much! That helps a lot!
