### ISSUE TITLE
Experiment-related question

### ISSUE THREAD

**Issue by zhaodongliang678** [RenShuhuai-Andy/TimeChat#21]
"First of all, thank you very much for your excellent work. 
Secondly, I have some questions to ask you: I validated on the Charades-STA dataset and got an IOU of 0.5: 29.327956989247312, which differs by a few percentage points from the paper. I saw before that you reposted the checkpoint from the paper in the issues, but now I can't find the checkpoint from the paper. Could you please repost them again? Thank you very much for your assistance, and I look forward to your reply."

**Comment by onlyonewater** [comment]
you can download from the https://hf-mirror.com/ShuhuaiRen/TimeChat-7b-paper by using the huggingface-cli tools

**Comment by RenShuhuai-Andy** [comment]
thanks @onlyonewater for clarification! yes you can found the ckpt used in our paper from https://huggingface.co/ShuhuaiRen/TimeChat-7b-paper

**Comment by zhaodongliang678** [comment]
Thank you for your response!
