### ISSUE TITLE
Question about batch size

### ISSUE THREAD

**Issue by gyxxyg** [RenShuhuai-Andy/TimeChat#23]
Hello, I attempted to replicate the results from the paper using the specified settings. According to the paper, the experiments were conducted on a single server with 8 V100 GPUs, and the total batch size was 32. Consequently, the batch size for each GPU should be 4. However, when I used this value, the training consistently failed.

Could you please provide the training scripts that were used in the paper? I would greatly appreciate your assistance.

**Comment by RenShuhuai-Andy** [comment]
Hi, what does `"The Training Consistently Failed"` mean?

Do you mean gpu out-of-memory? If so, please refer to https://github.com/RenShuhuai-Andy/TimeChat/issues/10#issuecomment-1959292668
