### ISSUE TITLE
Checkpoints to run demo and dataset

### ISSUE THREAD

**Issue by fazlicodes** [RenShuhuai-Andy/TimeChat#3]
Great work, is it possible for me to know when will the checkpoints to run the demo locally and complete datasets be released?

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interest. 

We have now released TimeChat-7b [checkpoint](https://huggingface.co/ShuhuaiRen/TimeChat-7b) and [local demo](./demo.ipynb). Feel free to contact us if there are any problems.
