### ISSUE TITLE
Asking for the Fine-tuned Checkpoint

### ISSUE THREAD

**Issue by minjoong507** [RenShuhuai-Andy/TimeChat#35]
Hi, there.

Thanks for sharing your great work.

I'm trying to reproduce the results on Charades-STA (reported in Table 5 in the paper), but it seems like there is only a checkpoint file, fine-tuned on video instruction tuning datasets.

Could you please provide the checkpoint (fine-tuned on Charades-STA)?

**Comment by RenShuhuai-Andy** [comment]
Hi, the ckpt has been uploaded to https://huggingface.co/ShuhuaiRen/TimeChat-7b-Charades-STA-ft.

**Comment by minjoong507** [comment]
Thanks for your reply :)
