### ISSUE TITLE
Weight for QA benchmarks

### ISSUE THREAD

**Issue by NIneeeeeem** [RenShuhuai-Andy/TimeChat#36]
Hi, there. Thanks for sharing your great work.

I wonder if the performance on the recently released QA benchmarks is zeroshot performance. Or rather, whether the original TimeChat weights have been imported or if there are new fine-tuned weights？

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interest.

We conduct **zero-shot** evaluation on the QA benchmarks using the original [TimeChat weights](https://huggingface.co/ShuhuaiRen/TimeChat-7b).

**Comment by NIneeeeeem** [comment]
@RenShuhuai-Andy  Thanks very mach for your reply, I just tested the performance of zeroshot and it does have good performance on open-set VQA. 

However, there is no output that matches the form on benchmarks with multiple choice questions such as EgoScheme. This type of problem also occurs in many models that have not been fine-tuned for multiple choice questions, and I wonder if you have a good solution for this!

**Comment by NIneeeeeem** [comment]
Thank you for sharing your work! No problem now.
