### ISSUE TITLE
UnsatisfiableError

### ISSUE THREAD

**Issue by LarryLeeee** [RenShuhuai-Andy/TimeChat#4]
There is something wrong when I tried to create the conda environment.
![75069b3e9fad35cfb90ef4faabe0b70](https://github.com/RenShuhuai-Andy/TimeChat/assets/116328167/fcdeaa84-f685-463f-91f1-ec0c8b6beb5c)
I have searched some of the common solutions on the Internet, but none of them worked.

**Comment by RenShuhuai-Andy** [comment]
Hi, I have re-tried to create the conda environment based on `environment.yml`, it works on my device.

Can you just remove the line of `_openmp_mutex=5.1=1_gnu` in https://github.com/RenShuhuai-Andy/TimeChat/blob/master/environment.yml#L7 and try it again?

**Comment by LarryLeeee** [comment]
The problem has already been fixed by removing the version, because they are different on my RedHat machine.Thx!

**Comment by LarryLeeee** [comment]
And there's a new problem when I directly bash eval.sh
![243a876c8e54c0ed653df47fba08416](https://github.com/RenShuhuai-Andy/TimeChat/assets/116328167/4a4079c2-176d-4387-a498-c5ba0b29d32e)
Could you please upload this file and relevant checkpoints?
