### ISSUE TITLE
q-former和llama的词典不一样，一个是bert，一个是llama。能通用吗？

### ISSUE THREAD

**Issue by guantao18** [RenShuhuai-Andy/TimeChat#43]
![image](https://github.com/user-attachments/assets/f3340840-54b0-4847-a861-008d364f3596)

**Comment by RenShuhuai-Andy** [comment]
Hi, please refer to https://github.com/RenShuhuai-Andy/TimeChat/blob/master/docs/FAQ.md#4-implementation-of-the-time-aware-frame-encoder
