### ISSUE TITLE
how to evaluation on activitynet-DVC?

### ISSUE THREAD

**Issue by TXH-mercury** [RenShuhuai-Andy/TimeChat#6]
Thanks for the good job!
I want to evaluate dvc on activitynet captions, there are val1 and val2 two annotations, how to modify the code?

**Comment by RenShuhuai-Andy** [comment]
Hi, the annotation files and processing code that I uploaded yesterday have something wrong. I have updated them just now. Please re-download them, sorry about that. 

We recommend to run our [processing code](https://github.com/RenShuhuai-Andy/TimeChat/blob/master/utils/get_coco_format.py#L87) by yourself to ensure that all the broken local videos are filtered.

**Comment by RenShuhuai-Andy** [comment]
For your information, we evaluate the performance of TimeChat-7B on anet dvc, the results are:
![image](https://github.com/RenShuhuai-Andy/TimeChat/assets/30052148/44b08aa4-64b1-4a92-9759-d35606a9b461)
