### ISSUE TITLE
the generalization performance is bad when testing on custom videos.

### ISSUE THREAD

**Issue by dragen1860** [RenShuhuai-Andy/TimeChat#8]
Hi, thanks for publishing the work.
  Although its an really insightful work, but i have to say, the performance is not so good when talking about generalization.  I tried some custom in the wild video and the timestamp is unreasonable and the summarization text is also not relevant with video.  Have you tested on your own videos? does it perform good?  .

**Comment by RenShuhuai-Andy** [comment]
Hi, thanks for your interest.

Can you show the specific case you tested, including screenshot of the key frame, duration of the video, prompt, and the model output? As we shown in Table 2, the zero-shot performance of the model is indeed far from satisfaction in actual usage, However, the model is not expected to produce content that is entirely irrelevant.
