### ISSUE TITLE
torch.load raise TypeError: 'strict' is an invalid keyword argument for Unpickler()

### ISSUE THREAD

**Issue by wwq66** [RenShuhuai-Andy/TimeChat#9]
raise TypeError: 'strict' is an invalid keyword argument for Unpickler() when running the code below. It seems torch.load does not have the keyword 'strict'.
```
def _load_checkpoint(self, url_or_filename):
        """
        Resume from a checkpoint.
        """
        if is_url(url_or_filename):
            cached_file = download_cached_file(url_or_filename, check_hash=False, progress=True)
            checkpoint = torch.load(cached_file, map_location=self.device, strict=False)
        elif os.path.isfile(url_or_filename):
            print("url_or_filename: ", url_or_filename)
            checkpoint = torch.load(url_or_filename, map_location=self.device, strict=False)
        else:
            raise RuntimeError("checkpoint url or path is invalid")
```

**Comment by RenShuhuai-Andy** [comment]
Hi, what's your torch version?
You can try `pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118`

**Comment by wwq66** [comment]
I've tried torch version of 1.12.1, 1.13.1, 2.1.0, but none of these version works.
And the pytorch docs shows that torch.load do not have the keyword 'strict' as below.
<img width="887" alt="image" src="https://github.com/RenShuhuai-Andy/TimeChat/assets/32292809/c6dabdc7-0119-4284-b05f-096da282d0a3">
Only the load_state_dict have the 'strict' keyword
<img width="813" alt="image" src="https://github.com/RenShuhuai-Andy/TimeChat/assets/32292809/9586f7a7-d2ea-406d-81ce-c748a25f78df">

**Comment by RenShuhuai-Andy** [comment]
I see. I think you can directly remove the argument of `strict=False`. I will fix it later.

**Comment by wwq66** [comment]
Removing `strict` can actually fix the error. But seems to raise another error about missing keys while loading state_dict. I'll close this issue temporarily and try to fix the missing keys error.
